{
 "title": "Network Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Access Points ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slow APs Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "// First, get the last channel utilization for each AP\nlast_utilization = from(bucket: \"my-bucket\")\n    |> range(start: -5m)\n    |> filter(fn: (r) => r._measurement == \"ruckus_ap_metrics\" and r._field == \"channel_utilization_5ghz\")\n    |> group(columns: [\"ap_name\"])\n    |> last()\n    |> filter(fn: (r) => r._value > 75) // Find the slow APs\n    |> keep(columns: [\"ap_name\", \"_value\"])\n    |> rename(columns: {_value: \"utilization\"})\n\n// Second, get the last client count for each AP\nlast_client_count = from(bucket: \"my-bucket\")\n    |> range(start: -5m)\n    |> filter(fn: (r) => r._measurement == \"ruckus_ap_metrics\" and r._field == \"client_count\")\n    |> group(columns: [\"ap_name\"])\n    |> last()\n    |> keep(columns: [\"ap_name\", \"_value\"])\n    |> rename(columns: {_value: \"clients\"})\n\n// Join the two results together based on the AP name\njoin(\n    tables: {util: last_utilization, clients: last_client_count},\n    on: [\"ap_name\"]\n)\n|> sort(columns: [\"utilization\"], desc: true)\n|> group() "
    }
   ]
  },
  {
   "title": "Slow APs (High Utilization)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"channel_utilization_5ghz\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value > 75)\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Offline AP Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"status\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group() // Ungroup to turn the 'ap_name' tag into a column\n  |> keep(columns: [\"ap_name\", \"_time\"]) // Now this will work correctly\n  |> sort(columns: [\"ap_name\"])"
    }
   ]
  },
  {
   "title": "APs Offline",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"status\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Switchs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICX 8200 - Ports Up",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\" // Filter for the first switch\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1) // Filter for \"Up\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "ICX 8200 - Ports Down",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\" // Filter for the first switch\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0) // Filter for \"Down\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "ICX 8200 - Ports Empty",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2) // Filter for \"Empty\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "ICX 8100 - Ports Up",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\" // Filter for the first switch\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1) // Filter for \"Up\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "ICX 8100 - Ports Down",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\" // Filter for the first switch\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0) // Filter for \"Down\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "ICX 8100 - Ports Empty",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "/ 24" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2) // Filter for \"Empty\" status\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "Ruckus ICX 8200 Switch",
     "type": "canvas",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])"
      }
     ]
    },
    {
     "title": "Ruckus ICX 8100 Switch",
     "type": "canvas",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])"
      }
     ]
    }
   ]
  }
 ]
}