{
 "title": "Server monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\n  hrStorageUsed{job=\"snmp-servers\", hrStorageDescr=~\"/.*\"}\n  / \n  hrStorageSize{job=\"snmp-servers\", hrStorageDescr=~\"/.*\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (hrProcessorLoad{job=\"snmp-servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " CPU Utilization panel",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hrProcessorLoad{job=\"snmp-servers\"}",
     "legendFormat": "CPU {{hrProcessorIndex}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (hrProcessorLoad{job=\"snmp-servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n    hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"1\"}\n  /\n    hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"1\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"1\"} / hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"1\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 * (hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"10\"} / hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"10\"})",
     "legendFormat": "Swap"
    }
   ]
  }
 ]
}