{
 "title": "Temprature Sensor Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Temperature Trend (24h / 7d)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Max Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Ambient Room Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: mean,\n      createEmpty: false\n  )\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Average Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Min Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> min()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"environment\" and\r\n    r._field == \"humidity\" and\r\n    r.location == \"server_room\"\r\n  )\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: mean,\r\n      createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Ambient Room Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"humidity\" and\n    r.location == \"server_room\"\n  )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Humidity Trend (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"humidity\" and\n    r.location == \"server_room\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  }
 ]
}